### ISSUE TITLE
error on mac os

### ISSUE THREAD

**Issue by dousuguang** [conda-forge/nlopt-feedstock#17]
Issue:

Fatal Python error: PyThreadState_Get: no current thread

Abort trap: 6

<br/>
Environment (<code>conda list</code>):
<details>
mac os 10.11.6
```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jschueller** [comment]
conda list?

**Comment by dousuguang** [comment]
I find an alternative version 2.4.2 on anaconda cloud and it works. sorry i did not store the conda list.  I hope the problem I met was a rare case. Thank you for building these wonderful tools.

**Comment by jschueller** [comment]
Probably you did not set conda-forge channel with top priority.
