### ISSUE TITLE
Doesn't work on Windows.

### ISSUE THREAD

**Issue by melund** [conda-forge/nlopt-feedstock#6]
@jschueller It looks like it is build for windows but it doesn't seem to work. I can also see that Windows is excluded from testing. Any reason for that?

```python
>>> import nlopt
ImportError: No module named 'nlopt'
```

**Comment by jschueller** [comment]
yep, upstream does not provide windows bindings in a stable version yet

**Comment by melund** [comment]
I see. Then either let it build an unstable version for Windows or disable the build for Windows. 

We really don't want defective packages in the conda-forge channel.,

**Comment by jschueller** [comment]
No, the c++ library is needed.

**Comment by melund** [comment]
Hmm. I see the problem. Could c++ lib be split into its own package? Right now we are picking up this non-working package since conda-forge has priority in our setup. What is the @conda-forge/core preferences in these situations?

**Comment by jschueller** [comment]
Is there a working package somewhere ?

**Comment by scopatz** [comment]
@melund you should be able to make a C++-only version in a new package on staged-recipes

**Comment by melund** [comment]
>Is there a working package somewhere?

@jschueller .. I created some manually, for python2 last year (`conda install -c melund nlopt`). It was a hack as I pretty much converted Gohlke's wheel distribution of nlopt to a conda-package. 

So I was pretty happy to see nlopt in conda-forge with python3 support. 

> @melund you should be able to make a C++-only version in a new package on staged-recipes

@scopatz Thanks. I will consider that if I don't don't find another workaround. But I would much rather help get the conda-forge to work.

@jschueller What is the issues that you see on windows? I can't find anything on unstable windows binaries on http://ab-initio.mit.edu/wiki/index.php/NLopt_on_Windows

**Comment by jschueller** [comment]
by unstable I meant not in a release, full cmake support is in git, see https://github.com/conda-forge/nlopt-feedstock/pull/7.

**Comment by melund** [comment]
@jschueller . Makes sense now.. @stevengj hasn't tagged new releases in GitHub for 2.5 years. And there is no response on the issues requesting it (https://github.com/stevengj/nlopt/issues/87). 

Maybe it would be OK to use the CMake files on github to build the windows version. It seems like that is what Gohlke did for his nlopt 2.4.2 windows wheels.
